// src/components/ModelSwitcher.tsx
import React, { useState, useEffect } from 'react';
import { ChevronRight, Loader2, AlertCircle, CheckCircle, Database, Brain } from 'lucide-react';
import { invoke } from '@tauri-apps/api/core';
import { toast } from '@/lib/utils/toast';
import { Progress } from '@/components/ui/progress';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Alert, AlertDescription } from '@/components/ui/alert';

interface Model {
  id: string;
  name: string;
  available: boolean;
  provider: string;
}

interface MemoryStats {
  total_entries: number;
  total_tokens: number;
  memory_usage_mb: number;
  sessions_count: number;
  models_count: number;
}

interface TransferPreview {
  total_memories: number;
  total_tokens: number;
  target_max_tokens: number;
  will_compress: boolean;
  type_distribution: Record<string, number>;
  priority_distribution: Record<string, number>;
  supports_tools: boolean;
  supports_images: boolean;
}

interface TransferResult {
  session_id: string;
  source_model: string;
  target_model: string;
  total_tokens: number;
  transfer_time_ms: number;
  success: boolean;
  message: string;
}

interface ModelSwitcherProps {
  currentModel: string;
  sessionId: string;
  models: Model[];
  onModelChange: (modelId: string) => void;
}

export function ModelSwitcher({ 
  currentModel, 
  sessionId, 
  models, 
  onModelChange 
}: ModelSwitcherProps) {
  const [selectedModel, setSelectedModel] = useState(currentModel);
  const [recommendedModel, setRecommendedModel] = useState<string>('');
  const [memoryStats, setMemoryStats] = useState<MemoryStats | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [transferPreview, setTransferPreview] = useState<TransferPreview | null>(null);
  const [isTransferring, setIsTransferring] = useState(false);
  const [lastTransferResult, setLastTransferResult] = useState<TransferResult | null>(null);

  useEffect(() => {
    loadMemoryStats();
    if (sessionId) {
      getRecommendation();
    }
  }, [sessionId]);

  const loadMemoryStats = async () => {
    try {
      const stats = await invoke<MemoryStats>('get_memory_stats');
      setMemoryStats(stats);
    } catch (error) {
      console.error('Failed to load memory stats:', error);
    }
  };

  const getRecommendation = async () => {
    try {
      const model = await invoke<string>('recommend_model_for_context', { sessionId });
      setRecommendedModel(model);
    } catch (error) {
      console.error('Failed to get recommendation:', error);
    }
  };

  const handleModelSelect = async (modelId: string) => {
    if (modelId === currentModel) return;
    
    setSelectedModel(modelId);
    
    if (!sessionId) {
      // No session context to transfer
      onModelChange(modelId);
      return;
    }

    // Preview the transfer
    try {
      const preview = await invoke<TransferPreview>('preview_context_transfer', {
        sessionId,
        sourceModel: currentModel,
        targetModel: modelId
      });
      setTransferPreview(preview);
      setShowPreview(true);
    } catch (error) {
      console.error('Failed to preview transfer:', error);
      toast.error('Failed to preview context transfer');
    }
  };

  const confirmTransfer = async () => {
    if (!selectedModel || !sessionId) return;

    setIsTransferring(true);
    try {
      const result = await invoke<TransferResult>('transfer_context_to_model', {
        sessionId,
        sourceModel: currentModel,
        targetModel: selectedModel
      });

      if (result.success) {
        setLastTransferResult(result);
        toast.success(`Context transferred in ${result.transfer_time_ms}ms`);
        onModelChange(selectedModel);
        setShowPreview(false);
        await loadMemoryStats();
      } else {
        toast.error(result.message || 'Transfer failed');
      }
    } catch (error) {
      console.error('Transfer failed:', error);
      toast.error('Failed to transfer context');
    } finally {
      setIsTransferring(false);
    }
  };

  const formatTokens = (count: number): string => {
    if (count > 1000000) return `${(count / 1000000).toFixed(1)}M`;
    if (count > 1000) return `${(count / 1000).toFixed(1)}K`;
    return count.toString();
  };

  return (
    <div className="model-switcher space-y-4 p-4 bg-card rounded-lg border">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold flex items-center gap-2">
          <Brain className="h-5 w-5" />
          AI Model
        </h3>
        {memoryStats && (
          <div className="flex items-center gap-4 text-sm text-muted-foreground">
            <span className="flex items-center gap-1">
              <Database className="h-4 w-4" />
              {formatTokens(memoryStats.total_tokens)} tokens
            </span>
            <span>{memoryStats.memory_usage_mb.toFixed(1)}MB</span>
          </div>
        )}
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
        {models.map((model) => {
          const isRecommended = model.id === recommendedModel;
          const isCurrent = model.id === currentModel;
          const isSelected = model.id === selectedModel;

          return (
            <Button
              key={model.id}
              variant={isCurrent ? 'default' : isSelected ? 'secondary' : 'outline'}
              size="sm"
              disabled={!model.available || isTransferring}
              onClick={() => handleModelSelect(model.id)}
              className={`relative ${isRecommended ? 'ring-2 ring-green-500' : ''}`}
            >
              <span className="truncate">{model.name}</span>
              {isRecommended && (
                <span className="absolute -top-2 -right-2 px-1 py-0.5 text-xs bg-green-500 text-white rounded">
                  Recommended
                </span>
              )}
              {!model.available && (
                <span className="absolute inset-0 bg-background/80 flex items-center justify-center text-xs">
                  Unavailable
                </span>
              )}
            </Button>
          );
        })}
      </div>

      {lastTransferResult && (
        <Alert className="bg-green-500/10 border-green-500/30">
          <CheckCircle className="h-4 w-4 text-green-500" />
          <AlertDescription>
            Last transfer: {lastTransferResult.source_model} → {lastTransferResult.target_model} 
            ({formatTokens(lastTransferResult.total_tokens)} tokens in {lastTransferResult.transfer_time_ms}ms)
          </AlertDescription>
        </Alert>
      )}

      <Dialog open={showPreview} onOpenChange={setShowPreview}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Context Transfer Preview</DialogTitle>
            <DialogDescription>
              Transfer conversation context from {currentModel} to {selectedModel}
            </DialogDescription>
          </DialogHeader>

          {transferPreview && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Memories to Transfer</label>
                  <div className="text-2xl font-bold">{transferPreview.total_memories}</div>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Total Tokens</label>
                  <div className="text-2xl font-bold">
                    <span className={transferPreview.will_compress ? 'text-orange-500' : ''}>
                      {formatTokens(transferPreview.total_tokens)}
                    </span>
                    <span className="text-sm text-muted-foreground">
                      {' / '}{formatTokens(transferPreview.target_max_tokens)}
                    </span>
                  </div>
                </div>
              </div>

              {transferPreview.will_compress && (
                <Alert className="bg-orange-500/10 border-orange-500/30">
                  <AlertCircle className="h-4 w-4 text-orange-500" />
                  <AlertDescription>
                    Context will be intelligently compressed to fit the target model's token limit
                  </AlertDescription>
                </Alert>
              )}

              {transferPreview.type_distribution && (
                <div className="space-y-2">
                  <label className="text-sm font-medium">Memory Type Distribution</label>
                  <div className="space-y-2">
                    {Object.entries(transferPreview.type_distribution).map(([type, count]) => (
                      <div key={type} className="flex items-center gap-2">
                        <span className="text-sm w-24">{type}:</span>
                        <div className="flex-1 bg-secondary rounded-full h-6 relative">
                          <div 
                            className="absolute inset-y-0 left-0 bg-primary rounded-full"
                            style={{ width: `${(count / transferPreview.total_memories) * 100}%` }}
                          />
                          <span className="absolute right-2 top-1/2 -translate-y-1/2 text-xs">
                            {count}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="flex items-center gap-4 text-sm">
                <div className="flex items-center gap-2">
                  <input type="checkbox" checked={transferPreview.supports_tools} readOnly />
                  <label>Tool Support</label>
                </div>
                <div className="flex items-center gap-2">
                  <input type="checkbox" checked={transferPreview.supports_images} readOnly />
                  <label>Image Support</label>
                </div>
              </div>
            </div>
          )}

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowPreview(false)} disabled={isTransferring}>
              Cancel
            </Button>
            <Button onClick={confirmTransfer} disabled={isTransferring}>
              {isTransferring ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Transferring...
                </>
              ) : (
                <>
                  <ChevronRight className="mr-2 h-4 w-4" />
                  Transfer Context
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// src/components/ModelSwitcher.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { fade, slide } from 'svelte/transition';
    import { 
        transferContext, 
        previewTransfer, 
        recommendModel,
        transferInProgress,
        memoryStats,
        type ContextTransferResult
    } from '$lib/stores/memoryStore';
    import { currentSession, currentModel } from '$lib/stores/sessionStore';
    import { toast } from '$lib/utils/toast';
    
    export let models: Array<{ id: string; name: string; available: boolean }> = [];
    export let onModelSwitch: (modelId: string) => void = () => {};
    
    let selectedModel = '';
    let showPreview = false;
    let transferPreview: Record<string, any> | null = null;
    let recommendedModel = '';
    let isTransferring = false;
    let lastTransferResult: ContextTransferResult | null = null;
    
    $: sessionId = $currentSession?.id || '';
    $: sourceModel = $currentModel || '';
    $: isTransferring = $transferInProgress;
    
    onMount(async () => {
        selectedModel = sourceModel;
        
        // Get model recommendation if we have a session
        if (sessionId) {
            try {
                recommendedModel = await recommendModel(sessionId);
            } catch (error) {
                console.error('Failed to get model recommendation:', error);
            }
        }
    });
    
    async function handleModelChange() {
        if (!selectedModel || selectedModel === sourceModel) {
            return;
        }
        
        if (!sessionId) {
            // No session, just switch
            onModelSwitch(selectedModel);
            return;
        }
        
        // Preview the transfer
        try {
            transferPreview = await previewTransfer(sessionId, sourceModel, selectedModel);
            showPreview = true;
        } catch (error) {
            console.error('Failed to preview transfer:', error);
            toast.error('Failed to preview context transfer');
        }
    }
    
    async function confirmTransfer() {
        if (!selectedModel || !sessionId) return;
        
        try {
            const result = await transferContext(sessionId, sourceModel, selectedModel);
            
            if (result.success) {
                lastTransferResult = result;
                toast.success(`Context transferred successfully in ${result.transfer_time_ms}ms`);
                onModelSwitch(selectedModel);
                showPreview = false;
            } else {
                toast.error(result.message || 'Failed to transfer context');
            }
        } catch (error) {
            console.error('Context transfer failed:', error);
            toast.error('Failed to transfer context to new model');
        }
    }
    
    function cancelTransfer() {
        showPreview = false;
        transferPreview = null;
        selectedModel = sourceModel;
    }
    
    function formatTokenCount(count: number): string {
        if (count > 1000000) {
            return `${(count / 1000000).toFixed(1)}M`;
        } else if (count > 1000) {
            return `${(count / 1000).toFixed(1)}K`;
        }
        return count.toString();
    }
</script>

<div class="model-switcher">
    <div class="switcher-header">
        <h3>AI Model</h3>
        {#if $memoryStats}
            <div class="memory-stats">
                <span class="stat-item">
                    <i class="icon-memory"></i>
                    {formatTokenCount($memoryStats.total_tokens)} tokens
                </span>
                <span class="stat-item">
                    <i class="icon-database"></i>
                    {$memoryStats.memory_usage_mb.toFixed(1)} MB
                </span>
            </div>
        {/if}
    </div>
    
    <div class="model-selector">
        <select 
            bind:value={selectedModel}
            on:change={handleModelChange}
            disabled={isTransferring}
            class:recommended={selectedModel === recommendedModel}
        >
            <option value="">Select a model...</option>
            {#each models as model}
                <option 
                    value={model.id} 
                    disabled={!model.available}
                >
                    {model.name}
                    {#if model.id === recommendedModel}
                        (Recommended)
                    {/if}
                    {#if !model.available}
                        (Unavailable)
                    {/if}
                </option>
            {/each}
        </select>
        
        {#if isTransferring}
            <div class="transfer-indicator" transition:fade>
                <div class="spinner"></div>
                <span>Transferring context...</span>
            </div>
        {/if}
    </div>
    
    {#if recommendedModel && recommendedModel !== selectedModel}
        <div class="recommendation" transition:slide>
            <i class="icon-info"></i>
            <span>Based on your current context, <strong>{recommendedModel}</strong> is recommended</span>
        </div>
    {/if}
    
    {#if showPreview && transferPreview}
        <div class="transfer-preview" transition:slide>
            <h4>Context Transfer Preview</h4>
            
            <div class="preview-stats">
                <div class="stat">
                    <label>Memories to Transfer:</label>
                    <span>{transferPreview.total_memories || 0}</span>
                </div>
                <div class="stat">
                    <label>Total Tokens:</label>
                    <span class:warning={transferPreview.will_compress}>
                        {formatTokenCount(transferPreview.total_tokens || 0)}
                        / {formatTokenCount(transferPreview.target_max_tokens || 0)}
                    </span>
                </div>
                {#if transferPreview.will_compress}
                    <div class="compression-warning">
                        <i class="icon-warning"></i>
                        Context will be compressed to fit token limit
                    </div>
                {/if}
            </div>
            
            {#if transferPreview.type_distribution}
                <div class="distribution">
                    <h5>Memory Types</h5>
                    <div class="distribution-bars">
                        {#each Object.entries(transferPreview.type_distribution) as [type, count]}
                            <div class="bar-item">
                                <label>{type}:</label>
                                <div class="bar">
                                    <div 
                                        class="bar-fill"
                                        style="width: {(count / transferPreview.total_memories) * 100}%"
                                    ></div>
                                    <span>{count}</span>
                                </div>
                            </div>
                        {/each}
                    </div>
                </div>
            {/if}
            
            <div class="preview-actions">
                <button 
                    class="btn-primary"
                    on:click={confirmTransfer}
                    disabled={isTransferring}
                >
                    Confirm Transfer
                </button>
                <button 
                    class="btn-secondary"
                    on:click={cancelTransfer}
                    disabled={isTransferring}
                >
                    Cancel
                </button>
            </div>
        </div>
    {/if}
    
    {#if lastTransferResult}
        <div class="transfer-result" transition:slide>
            <div class="result-header">
                <i class="icon-check"></i>
                <span>Last Transfer: {lastTransferResult.source_model} → {lastTransferResult.target_model}</span>
            </div>
            <div class="result-stats">
                <span>{lastTransferResult.transferred_memories.length} memories</span>
                <span>{formatTokenCount(lastTransferResult.total_tokens)} tokens</span>
                <span>{lastTransferResult.transfer_time_ms}ms</span>
            </div>
        </div>
    {/if}
</div>

<style>
    .model-switcher {
        background: var(--surface);
        border-radius: 8px;
        padding: 16px;
        margin-bottom: 16px;
    }
    
    .switcher-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 12px;
    }
    
    .switcher-header h3 {
        margin: 0;
        font-size: 16px;
        font-weight: 600;
    }
    
    .memory-stats {
        display: flex;
        gap: 12px;
        font-size: 12px;
        color: var(--text-secondary);
    }
    
    .stat-item {
        display: flex;
        align-items: center;
        gap: 4px;
    }
    
    .model-selector {
        position: relative;
    }
    
    select {
        width: 100%;
        padding: 8px 12px;
        border: 1px solid var(--border);
        border-radius: 6px;
        background: var(--background);
        font-size: 14px;
        cursor: pointer;
        transition: all 0.2s;
    }
    
    select:hover:not(:disabled) {
        border-color: var(--primary);
    }
    
    select:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }
    
    select.recommended {
        border-color: var(--success);
    }
    
    .transfer-indicator {
        position: absolute;
        top: 50%;
        right: 12px;
        transform: translateY(-50%);
        display: flex;
        align-items: center;
        gap: 8px;
        font-size: 12px;
        color: var(--primary);
    }
    
    .spinner {
        width: 16px;
        height: 16px;
        border: 2px solid var(--primary);
        border-top-color: transparent;
        border-radius: 50%;
        animation: spin 0.8s linear infinite;
    }
    
    @keyframes spin {
        to { transform: rotate(360deg); }
    }
    
    .recommendation {
        margin-top: 8px;
        padding: 8px 12px;
        background: var(--info-bg);
        border: 1px solid var(--info-border);
        border-radius: 6px;
        font-size: 13px;
        display: flex;
        align-items: center;
        gap: 8px;
    }
    
    .transfer-preview {
        margin-top: 16px;
        padding: 16px;
        background: var(--background);
        border: 1px solid var(--border);
        border-radius: 6px;
    }
    
    .transfer-preview h4 {
        margin: 0 0 12px 0;
        font-size: 14px;
        font-weight: 600;
    }
    
    .preview-stats {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
        gap: 12px;
        margin-bottom: 16px;
    }
    
    .stat {
        display: flex;
        flex-direction: column;
        gap: 4px;
    }
    
    .stat label {
        font-size: 12px;
        color: var(--text-secondary);
    }
    
    .stat span {
        font-size: 18px;
        font-weight: 600;
    }
    
    .stat span.warning {
        color: var(--warning);
    }
    
    .compression-warning {
        padding: 8px 12px;
        background: var(--warning-bg);
        border: 1px solid var(--warning-border);
        border-radius: 4px;
        font-size: 13px;
        display: flex;
        align-items: center;
        gap: 8px;
        margin-bottom: 12px;
    }
    
    .distribution {
        margin-bottom: 16px;
    }
    
    .distribution h5 {
        margin: 0 0 8px 0;
        font-size: 13px;
        font-weight: 600;
        color: var(--text-secondary);
    }
    
    .distribution-bars {
        display: flex;
        flex-direction: column;
        gap: 6px;
    }
    
    .bar-item {
        display: flex;
        align-items: center;
        gap: 8px;
        font-size: 12px;
    }
    
    .bar-item label {
        min-width: 100px;
        color: var(--text-secondary);
    }
    
    .bar {
        flex: 1;
        height: 20px;
        background: var(--surface);
        border-radius: 4px;
        position: relative;
        overflow: hidden;
    }
    
    .bar-fill {
        height: 100%;
        background: var(--primary);
        transition: width 0.3s ease;
    }
    
    .bar span {
        position: absolute;
        right: 8px;
        top: 50%;
        transform: translateY(-50%);
        font-size: 11px;
        font-weight: 600;
    }
    
    .preview-actions {
        display: flex;
        gap: 8px;
        justify-content: flex-end;
    }
    
    .btn-primary,
    .btn-secondary {
        padding: 8px 16px;
        border-radius: 6px;
        font-size: 13px;
        font-weight: 500;
        cursor: pointer;
        transition: all 0.2s;
        border: none;
    }
    
    .btn-primary {
        background: var(--primary);
        color: white;
    }
    
    .btn-primary:hover:not(:disabled) {
        background: var(--primary-hover);
    }
    
    .btn-secondary {
        background: var(--surface);
        color: var(--text);
        border: 1px solid var(--border);
    }
    
    .btn-secondary:hover:not(:disabled) {
        background: var(--background);
    }
    
    button:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }
    
    .transfer-result {
        margin-top: 12px;
        padding: 12px;
        background: var(--success-bg);
        border: 1px solid var(--success-border);
        border-radius: 6px;
        font-size: 13px;
    }
    
    .result-header {
        display: flex;
        align-items: center;
        gap: 8px;
        margin-bottom: 8px;
        font-weight: 500;
    }
    
    .result-stats {
        display: flex;
        gap: 16px;
        font-size: 12px;
        color: var(--text-secondary);
    }
</style>
